### ISSUE TITLE
Contentful management errors

### ISSUE THREAD

**Issue by msfragala** [contentful/contentful-extension-cli#8]
Encountering the following error when trying to use the `get`, `save`, or `delete` API methods:

```
TypeError: Cannot read property 'id' of undefined
    at new APIError (/Users/Mitchell/Repository/fmi-contentful/node_modules/contentful-management/lib/api-error.js:10:32)
    at /Users/Mitchell/Repository/fmi-contentful/node_modules/contentful-management/index.js:134:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

That error looks to be coming from the following line in `lib/api-error.js`:

```
this.name = error ? error.sys.id : 'Unknown error';
```

It looks like the API requests are all failing, and this library is hitting an error trying to handle those errors because `error.sys` is not defined.

Curious to see why the API requests were failing, I updated that line to avoid that error and tried using the `get` API method again. Encountered this confusing error message:

```
TypeError: Cannot use 'in' operator to search for 'message' in <html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?CWUDNSAI=18&xinfo=9-36323263-0 NNNN RT(1497537687783 24) q(0 0 0 -1) r(16 -1) B15(1,9,9) U5&incident_id=144000160124735905-244115663257338121&edet=15&cinfo=0100000006c7" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 144000160124735905-244115663257338121</iframe></body></html>
    at formatMessage (/Users/Mitchell/Repository/fmi-contentful/node_modules/contentful-management/lib/api-error.js:34:20)
    at new APIError (/Users/Mitchell/Repository/fmi-contentful/node_modules/contentful-management/lib/api-error.js:11:48)
    at /Users/Mitchell/Repository/fmi-contentful/node_modules/contentful-management/index.js:134:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

I should specify that this was working a little over a month ago when I tried updating a UI extension last. Nothing has changed in our code since then and we're using the latest version of this library, so it doesn't seem likely that I'm using the library wrong.

Instead, I noticed that this library uses v0.8.3 of the `contentful-management` library, which is currently up to v3.7.3. There's been a lot more work there than here, so it seems like this library may be out-of-date with the Contentful Management API.

**Comment by geigerzaehler** [comment]
Hi @msfragala. Thanks for reporting this issue. From you second code snippet it seems like our security system is blocking your request.

You can see that the response is an HTML string and not a JSON object. This is why an error is thrown when trying to access `error.sys.id`. The response also contains the string “Request unsuccessful. Incapsula incident ID: ...”. We will investigate what causes your request to be blocked. We will also improve our error handling for non-JSON response so that it helps you figure out what has happened.

**Comment by geigerzaehler** [comment]
It was indeed an issue with our firewall. The problem has been fixed an everything should be working again. Don’t hesitate to get back to us if it does not.
